//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT431Site.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GPUCard
    {
        public int GPUCardID { get; set; }
        public int ChipsetID { get; set; }
        public int ManufactureID { get; set; }
        public decimal Price { get; set; }
        public string MemoryType { get; set; }
        public string Memory { get; set; }
        public string ClockSpeed { get; set; }
        public string ImageLink { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Release Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    
        public virtual Chipset Chipset { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
