//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT431Site.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GraphicsCardsDataEntities : DbContext
    {
        public GraphicsCardsDataEntities()
            : base("name=GraphicsCardsDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chipset> Chipsets { get; set; }
        public virtual DbSet<GPUCard> GPUCards { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
    }
}
